"""empty message

Revision ID: 054888bdd2a9
Revises: 679a86a0ab81
Create Date: 2022-12-10 20:51:39.100591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054888bdd2a9'
down_revision = '679a86a0ab81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition_information', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'competition_information', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'competition_information', type_='foreignkey')
    op.drop_column('competition_information', 'user_id')
    # ### end Alembic commands ###
