"""empty message

Revision ID: 0f9af0c1dd49
Revises: 738838e4aad8
Create Date: 2022-11-20 12:43:04.489257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f9af0c1dd49'
down_revision = '738838e4aad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_table', sa.Column('match_id', sa.Integer(), nullable=True))
    op.drop_constraint('achievement_table_ibfk_1', 'achievement_table', type_='foreignkey')
    op.create_foreign_key(None, 'achievement_table', 'competition_information', ['match_id'], ['id'])
    op.drop_column('achievement_table', 'competition_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_table', sa.Column('competition_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'achievement_table', type_='foreignkey')
    op.create_foreign_key('achievement_table_ibfk_1', 'achievement_table', 'competition_information', ['competition_id'], ['id'])
    op.drop_column('achievement_table', 'match_id')
    # ### end Alembic commands ###
