"""empty message

Revision ID: 1049557e8073
Revises: 7b2736db2df6
Create Date: 2022-11-11 22:57:14.642904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1049557e8073'
down_revision = '7b2736db2df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_cuber_222', sa.Column('achievement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'achievement_cuber_222', 'achievement_table', ['achievement_id'], ['id'])
    op.add_column('achievement_cuber_333', sa.Column('achievement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'achievement_cuber_333', 'achievement_table', ['achievement_id'], ['id'])
    op.add_column('achievement_cuber_oh', sa.Column('achievement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'achievement_cuber_oh', 'achievement_table', ['achievement_id'], ['id'])
    op.add_column('achievement_cuber_py', sa.Column('achievement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'achievement_cuber_py', 'achievement_table', ['achievement_id'], ['id'])
    op.add_column('achievement_cuber_sk', sa.Column('achievement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'achievement_cuber_sk', 'achievement_table', ['achievement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'achievement_cuber_sk', type_='foreignkey')
    op.drop_column('achievement_cuber_sk', 'achievement_id')
    op.drop_constraint(None, 'achievement_cuber_py', type_='foreignkey')
    op.drop_column('achievement_cuber_py', 'achievement_id')
    op.drop_constraint(None, 'achievement_cuber_oh', type_='foreignkey')
    op.drop_column('achievement_cuber_oh', 'achievement_id')
    op.drop_constraint(None, 'achievement_cuber_333', type_='foreignkey')
    op.drop_column('achievement_cuber_333', 'achievement_id')
    op.drop_constraint(None, 'achievement_cuber_222', type_='foreignkey')
    op.drop_column('achievement_cuber_222', 'achievement_id')
    # ### end Alembic commands ###
