"""empty message

Revision ID: 1ee9c78abdaa
Revises: c4a02886ccf3
Create Date: 2022-12-02 18:09:59.382782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ee9c78abdaa'
down_revision = 'c4a02886ccf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement_cuber_222', 'best_3')
    op.drop_column('achievement_cuber_222', 'best_2')
    op.drop_column('achievement_cuber_333', 'best_3')
    op.drop_column('achievement_cuber_333', 'best_2')
    op.drop_column('achievement_cuber_oh', 'best_3')
    op.drop_column('achievement_cuber_oh', 'best_2')
    op.drop_column('achievement_cuber_py', 'best_3')
    op.drop_column('achievement_cuber_py', 'best_2')
    op.drop_column('achievement_cuber_sk', 'best_3')
    op.drop_column('achievement_cuber_sk', 'best_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_cuber_sk', sa.Column('best_2', mysql.FLOAT(), nullable=True))
    op.add_column('achievement_cuber_sk', sa.Column('best_3', mysql.FLOAT(), nullable=True))
    op.add_column('achievement_cuber_py', sa.Column('best_2', mysql.FLOAT(), nullable=True))
    op.add_column('achievement_cuber_py', sa.Column('best_3', mysql.FLOAT(), nullable=True))
    op.add_column('achievement_cuber_oh', sa.Column('best_2', mysql.FLOAT(), nullable=True))
    op.add_column('achievement_cuber_oh', sa.Column('best_3', mysql.FLOAT(), nullable=True))
    op.add_column('achievement_cuber_333', sa.Column('best_2', mysql.FLOAT(), nullable=True))
    op.add_column('achievement_cuber_333', sa.Column('best_3', mysql.FLOAT(), nullable=True))
    op.add_column('achievement_cuber_222', sa.Column('best_2', mysql.FLOAT(), nullable=True))
    op.add_column('achievement_cuber_222', sa.Column('best_3', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
