"""empty message

Revision ID: 307a20d22170
Revises: 1ee9c78abdaa
Create Date: 2022-12-03 02:21:04.647374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '307a20d22170'
down_revision = '1ee9c78abdaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'maxim')
    op.drop_column('user_profile', 'birthday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('birthday', sa.DATE(), nullable=True))
    op.add_column('user_profile', sa.Column('maxim', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
