"""empty message

Revision ID: 5935ad734a98
Revises: 6ee8c5209a14
Create Date: 2022-11-11 14:30:18.114941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5935ad734a98'
down_revision = '6ee8c5209a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_cuber_222', sa.Column('competition_options', sa.String(length=10), nullable=True))
    op.add_column('achievement_cuber_333', sa.Column('competition_options', sa.String(length=10), nullable=True))
    op.add_column('achievement_cuber_oh', sa.Column('competition_options', sa.String(length=10), nullable=True))
    op.add_column('achievement_cuber_py', sa.Column('competition_options', sa.String(length=10), nullable=True))
    op.add_column('achievement_cuber_sk', sa.Column('competition_options', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievement_cuber_sk', 'competition_options')
    op.drop_column('achievement_cuber_py', 'competition_options')
    op.drop_column('achievement_cuber_oh', 'competition_options')
    op.drop_column('achievement_cuber_333', 'competition_options')
    op.drop_column('achievement_cuber_222', 'competition_options')
    # ### end Alembic commands ###
