"""empty message

Revision ID: 60612d027341
Revises: 0b23d22aba3a
Create Date: 2022-11-19 16:57:26.267187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60612d027341'
down_revision = '0b23d22aba3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', sa.Date, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birthday')
    # ### end Alembic commands ###
