"""empty message

Revision ID: 628293cde926
Revises: d4f27e46bb0a
Create Date: 2022-11-20 12:47:10.843832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '628293cde926'
down_revision = 'd4f27e46bb0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_table', sa.Column('match_id1', sa.Integer(), nullable=True))
    op.drop_constraint('achievement_table_ibfk_1', 'achievement_table', type_='foreignkey')
    op.create_foreign_key(None, 'achievement_table', 'competition_information', ['match_id1'], ['id'])
    op.drop_column('achievement_table', 'match_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_table', sa.Column('match_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'achievement_table', type_='foreignkey')
    op.create_foreign_key('achievement_table_ibfk_1', 'achievement_table', 'competition_information', ['match_id'], ['id'])
    op.drop_column('achievement_table', 'match_id1')
    # ### end Alembic commands ###
