"""empty message

Revision ID: 679a86a0ab81
Revises: aec8d6b0a1f5
Create Date: 2022-12-07 13:25:10.706341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679a86a0ab81'
down_revision = 'aec8d6b0a1f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_time', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_article')
    # ### end Alembic commands ###
