"""empty message

Revision ID: 6ee8c5209a14
Revises: 89431e7f3323
Create Date: 2022-11-11 14:21:53.182642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ee8c5209a14'
down_revision = '89431e7f3323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_cuber_222',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('t1', sa.Float(), nullable=True),
    sa.Column('t2', sa.Float(), nullable=True),
    sa.Column('t3', sa.Float(), nullable=True),
    sa.Column('t4', sa.Float(), nullable=True),
    sa.Column('t5', sa.Float(), nullable=True),
    sa.Column('best', sa.Float(), nullable=True),
    sa.Column('best_2', sa.Float(), nullable=True),
    sa.Column('best_3', sa.Float(), nullable=True),
    sa.Column('ao5', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['competition_information.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('achievement_cuber_333',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('t1', sa.Float(), nullable=True),
    sa.Column('t2', sa.Float(), nullable=True),
    sa.Column('t3', sa.Float(), nullable=True),
    sa.Column('t4', sa.Float(), nullable=True),
    sa.Column('t5', sa.Float(), nullable=True),
    sa.Column('best', sa.Float(), nullable=True),
    sa.Column('best_2', sa.Float(), nullable=True),
    sa.Column('best_3', sa.Float(), nullable=True),
    sa.Column('ao5', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['competition_information.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('achievement_cuber_oh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('t1', sa.Float(), nullable=True),
    sa.Column('t2', sa.Float(), nullable=True),
    sa.Column('t3', sa.Float(), nullable=True),
    sa.Column('t4', sa.Float(), nullable=True),
    sa.Column('t5', sa.Float(), nullable=True),
    sa.Column('best', sa.Float(), nullable=True),
    sa.Column('best_2', sa.Float(), nullable=True),
    sa.Column('best_3', sa.Float(), nullable=True),
    sa.Column('ao5', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['competition_information.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('achievement_cuber_py',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('t1', sa.Float(), nullable=True),
    sa.Column('t2', sa.Float(), nullable=True),
    sa.Column('t3', sa.Float(), nullable=True),
    sa.Column('t4', sa.Float(), nullable=True),
    sa.Column('t5', sa.Float(), nullable=True),
    sa.Column('best', sa.Float(), nullable=True),
    sa.Column('best_2', sa.Float(), nullable=True),
    sa.Column('best_3', sa.Float(), nullable=True),
    sa.Column('ao5', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['competition_information.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('achievement_cuber_sk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('t1', sa.Float(), nullable=True),
    sa.Column('t2', sa.Float(), nullable=True),
    sa.Column('t3', sa.Float(), nullable=True),
    sa.Column('t4', sa.Float(), nullable=True),
    sa.Column('t5', sa.Float(), nullable=True),
    sa.Column('best', sa.Float(), nullable=True),
    sa.Column('best_2', sa.Float(), nullable=True),
    sa.Column('best_3', sa.Float(), nullable=True),
    sa.Column('ao5', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['competition_information.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('maxim', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('achievement')
    op.add_column('player_information', sa.Column('uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'player_information', 'user', ['uid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player_information', type_='foreignkey')
    op.drop_column('player_information', 'uid')
    op.create_table('achievement',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ach_222', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('ach_333', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('ach_333oh', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('ach_sk', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('ach_py', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('uid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['competition_information.id'], name='achievement_ibfk_1'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], name='achievement_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_profile')
    op.drop_table('achievement_cuber_sk')
    op.drop_table('achievement_cuber_py')
    op.drop_table('achievement_cuber_oh')
    op.drop_table('achievement_cuber_333')
    op.drop_table('achievement_cuber_222')
    # ### end Alembic commands ###
