"""empty message

Revision ID: 738838e4aad8
Revises: d7f250767eaa
Create Date: 2022-11-19 23:10:04.676579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '738838e4aad8'
down_revision = 'd7f250767eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('achievement_table_ibfk_2', 'achievement_table', type_='foreignkey')
    op.drop_column('achievement_table', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_table', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('achievement_table_ibfk_2', 'achievement_table', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
