"""empty message

Revision ID: 78e34e08e148
Revises: 628293cde926
Create Date: 2022-11-20 12:48:42.870035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78e34e08e148'
down_revision = '628293cde926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_table', sa.Column('match_id', sa.Integer(), nullable=True))
    op.drop_constraint('achievement_table_ibfk_1', 'achievement_table', type_='foreignkey')
    op.create_foreign_key(None, 'achievement_table', 'competition_information', ['match_id'], ['id'])
    op.drop_column('achievement_table', 'match_id1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_table', sa.Column('match_id1', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'achievement_table', type_='foreignkey')
    op.create_foreign_key('achievement_table_ibfk_1', 'achievement_table', 'competition_information', ['match_id1'], ['id'])
    op.drop_column('achievement_table', 'match_id')
    # ### end Alembic commands ###
