"""empty message

Revision ID: aec8d6b0a1f5
Revises: 307a20d22170
Create Date: 2022-12-05 20:45:41.373494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aec8d6b0a1f5'
down_revision = '307a20d22170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('achievement_cuber_222_ibfk_2', 'achievement_cuber_222', type_='foreignkey')
    op.drop_column('achievement_cuber_222', 'achievement_id')
    op.drop_constraint('achievement_cuber_333_ibfk_2', 'achievement_cuber_333', type_='foreignkey')
    op.drop_column('achievement_cuber_333', 'achievement_id')
    op.drop_constraint('achievement_cuber_oh_ibfk_2', 'achievement_cuber_oh', type_='foreignkey')
    op.drop_column('achievement_cuber_oh', 'achievement_id')
    op.drop_constraint('achievement_cuber_py_ibfk_2', 'achievement_cuber_py', type_='foreignkey')
    op.drop_column('achievement_cuber_py', 'achievement_id')
    op.drop_constraint('achievement_cuber_sk_ibfk_2', 'achievement_cuber_sk', type_='foreignkey')
    op.drop_column('achievement_cuber_sk', 'achievement_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_cuber_sk', sa.Column('achievement_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('achievement_cuber_sk_ibfk_2', 'achievement_cuber_sk', 'achievement_table', ['achievement_id'], ['id'])
    op.add_column('achievement_cuber_py', sa.Column('achievement_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('achievement_cuber_py_ibfk_2', 'achievement_cuber_py', 'achievement_table', ['achievement_id'], ['id'])
    op.add_column('achievement_cuber_oh', sa.Column('achievement_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('achievement_cuber_oh_ibfk_2', 'achievement_cuber_oh', 'achievement_table', ['achievement_id'], ['id'])
    op.add_column('achievement_cuber_333', sa.Column('achievement_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('achievement_cuber_333_ibfk_2', 'achievement_cuber_333', 'achievement_table', ['achievement_id'], ['id'])
    op.add_column('achievement_cuber_222', sa.Column('achievement_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('achievement_cuber_222_ibfk_2', 'achievement_cuber_222', 'achievement_table', ['achievement_id'], ['id'])
    # ### end Alembic commands ###
