"""empty message

Revision ID: c4a02886ccf3
Revises: b15aef6d7e2e
Create Date: 2022-11-24 17:44:59.259444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a02886ccf3'
down_revision = 'b15aef6d7e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition_information', sa.Column('enter_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competition_information', 'enter_status')
    # ### end Alembic commands ###
