"""empty message

Revision ID: d4f27e46bb0a
Revises: 0f9af0c1dd49
Create Date: 2022-11-20 12:45:37.997685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4f27e46bb0a'
down_revision = '0f9af0c1dd49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', sa.String(length=16), nullable=True))
    op.drop_column('user_profile', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('sex', mysql.VARCHAR(length=16), nullable=True))
    op.drop_column('user', 'sex')
    # ### end Alembic commands ###
