"""empty message

Revision ID: d7f250767eaa
Revises: 60612d027341
Create Date: 2022-11-19 17:57:10.965593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f250767eaa'
down_revision = '60612d027341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'user', ['password'], unique=False)
    # ### end Alembic commands ###
