"""empty message

Revision ID: d985c0141ee5
Revises: bf870ebf646f
Create Date: 2022-12-14 19:28:07.519196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd985c0141ee5'
down_revision = 'bf870ebf646f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_password', sa.String(length=512), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('user', 'hash_password')
    # ### end Alembic commands ###
